plugins {
    id 'multiloader-loader'
    id 'net.fabricmc.fabric-loom'
}

dependencies {
    minecraft "com.mojang:minecraft:${mc_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
}

loom {
    runs {
        configureEach {
            ideConfigGenerated(true)
        }
        client {
            client()
            setConfigName('Fabric Client')
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            runDir('runs/server')
        }
    }
}

