modLoader = "javafml"
loaderVersion = "[1,)"
license = "${license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "${mod_author}"
logoFile = "assets/${mod_id}/icon.png"
# Server-side only: players without the mod can join
displayTest = "IGNORE_SERVER_VERSION"
description = '''
${mod_description}
'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${neoforge_range}"
ordering = "NONE"
side = "BOTH"
